name: Daily Task Tracker

on:
  schedule:
    - cron: '59 17 * * *'  # Runs at 11:59 AM UTC daily
  workflow_dispatch:      # Optional: Manual trigger for testing

jobs:
  run-daily-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          cd scripts
          pip install -r requirements.txt || true
          cd ..

      - name: Run task_tracker.py
        run: |
          cd scripts
          python task_tracker.py
          cd ..
      
      - name: Run word replacement script
        run: |
          cd scripts
          python word_replacer.py
          cd ..

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ACTION_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-update by task_tracker.py [$(date -u +'%Y-%m-%dT%H:%M:%SZ')]"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
